version: "3.4"

services:
  db:
    container_name: prisma-bench-db
    platform: linux/amd64
    image: mysql:5.7
    restart: on-failure
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=tester
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_DATABASE=test
      - TZ=Asia/Seoul
    volumes:
      - ./volume/db:/var/lib/mysql
    command: |
      --sql_mode=NO_ENGINE_SUBSTITUTION --default_storage_engine=InnoDB
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
